1
js-tasks-ru/jsbasic-20231211_ilyanich pull request #4
Opened 2023-12-18 18:42 UTC by Ilya-meidzi

2023-12-18 18:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-23 11:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-26 00:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-26 00:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-26 12:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-26 13:46 UTC, koalex requested changes
Исправить замечания

2023-12-26 13:46 UTC, koalex commented on 3-module/4-task/index.js
> +let result = showSalary(users, age);
Удалить эту строку (откуда взялись `users` и `age` ?)

2023-12-26 13:46 UTC, koalex commented on 3-module/5-task/index.js
> +console.log(getMinMax(inputData));
Удалить эту строку (откуда взялась `inputData`?)

2023-12-28 23:28 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-12-29 04:21 UTC, koalex approved these changes

2023-12-29 04:21 UTC, koalex commented on 3-module/5-task/index.js
> +  console.log(arr);
Не забывайте удалять `console.log`-и

2023-12-29 04:21 UTC, merged